services:
  spark-master:
    build:
      context: ./spark
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - spark-warehouse:/opt/bitnami/spark/spark-warehouse 
      - ./spark/notebooks:/opt/bitnami/spark/notebooks
    environment:
      - SPARK_MODE=master
      - HOME=/opt/bitnami/spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker:
    build:
      context: ./spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - HOME=/opt/bitnami/spark
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - spark-warehouse:/opt/bitnami/spark/spark-warehouse 
      - ./spark/notebooks:/opt/bitnami/spark/notebooks

  spark-worker-2:
    build:
      context: ./spark
    container_name: spark-worker-2
    depends_on:
      - spark-master
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8082:8081"
    environment:
      - SPARK_MODE=worker
      - HOME=/opt/bitnami/spark
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - spark-warehouse:/opt/bitnami/spark/spark-warehouse
      - ./spark/notebooks:/opt/bitnami/spark/notebooks

  jupyter-lab:
    build:
      context: ./spark
    container_name: jupyter-lab
    ports:
      - "8888:8888" 
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - spark-warehouse:/opt/bitnami/spark/spark-warehouse 
      - ./spark/notebooks:/opt/bitnami/spark/notebooks
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/opt/bitnami/spark
      - JUPYTER_ENABLE_LAB=yes
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
  spark-warehouse: